# Generated by Django 5.1.7 on 2025-07-17 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(default=1.5)),
                ('alert_level', models.IntegerField(choices=[(1, 'Warning (5+ reports)'), (2, 'High Alert (10+ reports)'), (3, 'Critical (20+ reports)')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-alert_level', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='crime_map_s_latitud_0e87b0_idx'), models.Index(fields=['created_at'], name='crime_map_s_created_040d39_idx')],
            },
        ),
    ]
