# Generated by Django 5.1.7 on 2025-07-18 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('report_type', models.CharField(choices=[('suspicious', 'Suspicious Activity'), ('petty', 'Petty Crime'), ('felony', 'Felony Crime'), ('other', 'Other Incident')], max_length=20)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('requires_followup', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SuspiciousPin',
        ),
        migrations.AddIndex(
            model_name='pindrop',
            index=models.Index(fields=['latitude', 'longitude'], name='crime_map_p_latitud_983bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='pindrop',
            index=models.Index(fields=['created_at'], name='crime_map_p_created_e495e3_idx'),
        ),
        migrations.AddIndex(
            model_name='pindrop',
            index=models.Index(fields=['report_type'], name='crime_map_p_report__d8da83_idx'),
        ),
    ]
