# Generated by Django 5.1.7 on 2025-08-03 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crime_map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pindrop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pindrop',
            index=models.Index(fields=['latitude', 'longitude'], name='crime_map_p_latitud_983bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='pindrop',
            index=models.Index(fields=['created_at'], name='crime_map_p_created_e495e3_idx'),
        ),
        migrations.AddIndex(
            model_name='pindrop',
            index=models.Index(fields=['report_type'], name='crime_map_p_report__d8da83_idx'),
        ),
    ]
