# Generated by Django 5.1.7 on 2025-08-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_map', '0002_initial'),
        ('crime_map', '0002_pindrop_delete_suspiciouspin_and_more'),
    ]

    operations = [
    ]
