# Generated by Django 5.1.7 on 2025-03-23 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_crimetype_remove_post_body_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='identifiers',
        ),
        migrations.AddField(
            model_name='post',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='social.post')),
            ],
        ),
    ]
