# Generated by Django 5.1.7 on 2025-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='terms_accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
