# Generated by Django 5.1.7 on 2025-08-11 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='investigating_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='investigation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='investigation_status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('INVESTIGATED', 'Investigated'), ('CLOSED', 'Case Closed')], default='REPORTED', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='investigation_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('CITIZEN', 'Citizen'), ('POLICE', 'Police Officer'), ('SECURITY', 'Security Company')], default='CITIZEN', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('psira_number', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_tier', models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=20, null=True)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_calls_limit', models.IntegerField(default=1000)),
                ('api_calls_used', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_type', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('response_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('CITIZEN', 'Citizen'), ('POLICE', 'Police Officer'), ('SECURITY', 'Security Company')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MORE_INFO', 'More Information Required')], default='PENDING', max_length=20)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='verification/id_documents/')),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='verification/proof_documents/')),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='verification/additional/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('police_badge_number', models.CharField(blank=True, max_length=50, null=True)),
                ('police_station', models.CharField(blank=True, max_length=200, null=True)),
                ('police_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('psira_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_done', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
